### ISSUE TITLE
not working on windows getting No devices found with name or id matching 'windows'  ,  

### ISSUE THREAD

**Issue by kw2019ltd** [AppleEducate/flutter_everywhere#4]
C:\Users\moshe\Desktop\flutter_everywhere-master>flutter run -d windows
No devices found with name or id matching 'windows'

ENABLE_FLUTTER_DESKTOP=true

flutter 1.5

**Comment by AppleEducate** [comment]
try now with the latest. I try to keep it in sync with the master branch of flutter and the examples of desktop embedding. I use it on macOS and haven't tested on windows yet. Your feedback is valuable

**Comment by gedw99** [comment]
Hey @AppleEducate 
Nice stuff - will kick the tires

I have found using Azure pipelines the best way to do Desktop and Mobile CI. 
They have every OS you can imagine and the OS you hit is a real OS so you can run tests and stuff that rely on a real Desktops.

**Comment by AppleEducate** [comment]
Do that have mac environments too?

**Comment by stuartmorgan** [comment]
> No devices found with name or id matching 'windows'

@kw2019ltd See the [flutter-desktop-embedding README](https://github.com/google/flutter-desktop-embedding/blob/master/README.md); the desktop support here is from that project, and thus requires the same setup (but doesn't link to those instructions). Given your Flutter version your issue is likely that you are on stable, which as explained there won't work.

**Comment by AppleEducate** [comment]
@stuartmorgan I Updated the docs for Desktop here: https://github.com/AppleEducate/flutter_everywhere/tree/master/desktop
